// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjfyxthibduqjnkqkimu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqZnl4dGhpYmR1cWpua3FraW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjY5MTAsImV4cCI6MjA3NDYwMjkxMH0.gtuBrTDDJyM0hVG4H1sDLBtwFuu5v9A0vJpNHqZN7PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});